---
title: "Port Townsend Ferry Dock Weather"
output: html_document
---

<style type="text/css">
h1.title {
  text-align: center;
}
</style>


```{r include = FALSE}
library(tidyverse)
library(shiny)
library(ggtext)
library(data.table)
library(lubridate)
```

```{r include = FALSE}
Sys.setenv(TZ="America/Los_Angeles")

wind.rose <- function(x) {
  upper <- seq(from = 11.25, by = 22.5, length.out = 17)
  card1 <- c('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', 'N')
  ifelse(x>360 | x<0,NA,card1[findInterval(x,upper,rightmost.closed = T)+1])
}

# Query and clean data

weather <- fread("https://www.ndbc.noaa.gov/data/realtime2/PTWW1.txt", 
                 skip = 2,
                 na.strings = "MM",
                 encoding = "UTF-8",
                 colClasses = c(rep("character", 5), rep("numeric", 3), 
                                rep("factor", 4), rep("numeric", 3), rep("factor", 4)),
                 col.names = c("Year", "Month", "Day", "Hour", "Minute", "Wind.Dir", 
                               "Wind.Speed", "Gust", NA, NA, NA, NA, "Pressure", 
                               "Air.Temp", "Water.Temp", NA, NA, NA, NA))

weather <- weather[1:240,] %>%
  select(c("Year", "Month", "Day", "Hour", "Minute", "Wind.Dir", "Wind.Speed",
           "Gust", "Pressure", "Air.Temp", "Water.Temp")) %>%
  unite(Date, Year, Month, Day, sep = "-", remove = TRUE) %>%
  unite(Hours, Hour, Minute, sep = ":", remove = TRUE) %>%
  unite(Time, Date, Hours, sep = " ", remove = TRUE) %>%
  mutate(Time = as.POSIXct(Time, format = "%Y-%m-%d %H:%M")) %>%
  mutate(Time = case_when(
    dst(Time[1]) == TRUE ~ Time - 25200,
    dst(Time[1]) == FALSE ~ Time - 28800)) %>%
  mutate(Wind.Speed = Wind.Speed * 1.94384) %>%
  mutate(Gust = Gust *1.94384)


# Build plots 

dir.plot <- ggplot(weather, aes(x = Time)) + 
  geom_point(aes(y = wind.rose(Wind.Dir)), size = 1) +
  theme_bw() +
  labs(title = "**Wind Direction**") +
  theme(plot.title = element_markdown()) +
  ylab("") +
  xlab("") +
  scale_y_discrete(limits = c('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', 'N'))

bar.plot <- ggplot(weather, aes(x = Time)) + 
  geom_line(aes(y = Pressure), size = 1) +
  geom_hline(aes(yintercept = 1013.25), linetype = "dashed", color = "gray") +
  theme_bw() +
  labs(title = "**Barometric Pressure**") +
  theme(plot.title = element_markdown()) +
  ylab("Millibars") +
  xlab("")

rose <- ggplot(first(na.omit(weather[,1:3])), aes(x = Wind.Dir)) +
  coord_polar(theta = "x", start = 0, direction = 1) +
  geom_histogram(fill = "red", color = "gray10", bins = 30) +
  scale_x_continuous(breaks = seq(0, 359, 22.5), limits = c(0, 359), 
                     labels = c('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 
                                'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW')) +
  theme_minimal() +
  theme(
    axis.text.y = element_blank(),
    axis.title = element_blank())

if (any(is.na(weather$Gust)) == TRUE){
  weather <- weather %>%
    drop_na(Gust)
}

weather.plot <- ggplot(weather, aes(x =Time)) + 
  geom_line(aes(y = Wind.Speed), size = 1) +
  geom_line(aes(y = Gust), color = "#FF0000") +
  theme_bw() +
  labs(
    title = "**Wind Speed** and <span style='color:#FF0000;'>**Gust**</span></span>") +
  theme(plot.title = element_markdown()) +
  scale_y_continuous(breaks = seq(0, max(weather$Gust), 5)) +
  ylab("Knots") +
  xlab("")
```

<center><h3> **Current time: `r Sys.time()`**</h3></center>
<center><h3> **Last reading: `r first(na.omit(weather$Time))`**</h3></center>
<center><h3> **`r paste0(wind.rose(first(na.omit(weather$Wind.Dir))), " ",
           round(first(na.omit(weather$Wind.Speed)), 0), " knots ",
           "(", first(na.omit(weather$Wind.Dir)), "°)")`**</h3></center>


```{r echo = FALSE, warning = FALSE, fig.align = 'center'}
rose
weather.plot
bar.plot
dir.plot
```
